redfish:
  name: redfish-exporter
  enabled: false
  app_env: "production"
  image: redfish-exporter
  tag: '20211007193320'
  fullnameOverride: redfish-exporter
  listen_port: 9220
  namespace: infra-monitoring
  replicas: 1
  alerts:
    enabled: true
    prometheus: infra-collector
  exporterAlerts:
    enabled: true
    prometheus: infra-collector
  limits:
    memory: 200Mi
    cpu: 400m
  resources:
    memory: 100Mi
    cpu: 200m
global:
  registry: DEFINED-IN-GLOBAL-SECRETS
