{{- if .Values.simulator.poller.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: poller-simulator
  namespace: {{ .Release.Namespace }}
  labels:
    app: poller-simulator
    chart: poller-simulator
    release: poller-simulator
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.yaml: {{ include "poller-simulator/templates/_config.yaml.tpl" . | b64enc }}
{{- end -}}
