{{- if .Values.api.uwsgi }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc-api
  labels:
    system: openstack
    type: configuration
    component: neutron

data:
  uwsgi.ini: |
{{ include (print .Template.BasePath "/etc/_uwsgi.ini.tpl") . | indent 4 }}
  neutron-api.py: |
{{ include (print .Template.BasePath "/bin/_neutron-api.py") . | indent 4 }}
  gunicorn.conf.py: |
{{ include (print .Template.BasePath "/etc/_gunicorn.ini.tpl") . | indent 4 }}
{{- end }}