---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: volume-claims
    meta.helm.sh/release-namespace: monsoon3
  labels:
    app.kubernetes.io/managed-by: Helm
  name: db-cinder-pvclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
