---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: volume-claims
    meta.helm.sh/release-namespace: monsoon3
  labels:
    app.kubernetes.io/managed-by: Helm
  name: db-octavia-pvclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ if .Values.global.region | require ".Values.global.region missing" | regexMatch "^(?:ap-sa-2)$" -}} 50Gi {{- else -}} 10Gi {{- end }}
