kind: Service
apiVersion: v1

metadata:
  name: glance
  labels:
    application: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: glance
    type: api
spec:
  selector:
    app: {{ template "name" . }}
  type: {{ default "ClusterIP" .Values.services.type | quote }}
  ports:
    - name: public
      port: {{ .Values.api_port_internal }}
      targetPort: 9292
{{- if .Values.services.externalip }}
  externalIPs: [
    {{ .Values.services.externalip | quote }}
    ]
{{- end }}
