global:
  region: regionOne
  domain: evil.corp

authentication:
  enabled: true
  ssoCert: "valid certificate"
  ssoKey: "valid private key"

grafana:
  admin:
    username: admin
    password: topSecret!

extraScrapeConfig: |
  - job_name: 'dummy'

fluent-bit:
  filter:
    additionalValues:
    - key: superkey
      value: supervalue
  backend:
    es:
      logstash_prefix: lala
      host: host
      http_user: user
      http_passwd: pass
