{{- if .Values.poller.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: poller
  namespace: {{ .Release.Namespace }}
  labels:
    app: poller
    chart: poller
    release: poller
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.yaml: {{ include "cronus/templates/poller/_config.yaml.tpl" . | b64enc }}
{{- end -}}
