apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullName" . }}
  namespace: {{ .Values.redfish.namespace }}
  labels:
    app: {{ include "fullName" . }}
    type: exporter
spec:
  selector:
    app: {{ include "fullName" . }}
    type: exporter
  ports:
    - name: metrics
      port: {{ .Values.redfish.listen_port }}
