apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: mosquitto
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- range $ip := .Values.service.externalIPs }}
  - {{ $ip | quote }}
{{- end }}
{{ end }}
