{{- $probing := .Values.probing }}
{{- range $cluster_id, $cluster := .Values.clusters }}
{{- if not $cluster.tls_crt }}
kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: swift-{{$cluster_id}}
  annotations:
    # the ingress controller won't pick this up
    kubernetes.io/ingress.class: "noop.cert-manager"
    # enable cert-manager
    kubernetes.io/tls-acme: "true"
    {{- if $probing }}
    # enable probing
    prometheus.io/probe: "true"
    prometheus.io/probe_path: "/info"
    {{- end}}

# workaround to enable the vice-president for non-ingress based swift.
# the vp will only evaluate the following spec.tls section
spec:
  tls:
     - secretName: tls-swift-{{$cluster_id}}
       hosts: [{{$cluster.endpoint_host}}.{{$.Values.global.region}}.{{$.Values.global.tld}}
       {{- range $san := $cluster.sans }}, {{ printf "%s.%s.%s" $san $.Values.global.region $.Values.global.tld | quote }}{{ end }}
       {{- range $san := $cluster.sans_fqdn }}, {{ quote $san }}{{ end }}]
  # the following is mandatory in an ingress resource, but will be ignored by the vice-president
  rules:
    - host: {{$cluster.endpoint_host}}.{{$.Values.global.region}}.{{$.Values.global.tld}}
      http:
        paths:
        - path: /
          backend:
            serviceName: swift-{{$cluster_id}}
            servicePort: 9090
---
{{- end }}
{{- end }}
